name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install uv
        uv venv
        uv pip install -e '.[test]'

    - name: Activate virtualenv
      run: |
        . .venv/bin/activate
        echo PATH=$PATH >> $GITHUB_ENV
        
    - name: Run tests with pytest
      run: pytest

    - name: Build package
      run: python -m build --outdir dist/
