name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install uv
        uv venv
        uv pip install -e '.[test]'
        uv pip install build

    - name: Activate virtualenv
      run: |
        . .venv/bin/activate
        echo PATH=$PATH >> $GITHUB_ENV

    - name: Run tests with pytest
      run: pytest
