name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    
    - name: Extract version
      id: extract_version
      run: |
        echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "Ref name from GITHUB_REF: $GITHUB_REF"
        echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

    - name: Update pyproject version
      run: |
        echo ${{ steps.extract_version.outputs.tag }}
        pip install toml
        python -c "import toml; pyproject = toml.load('pyproject.toml'); pyproject['project']['version'] = '${{ steps.extract_version.outputs.tag }}'.strip()[1:]; toml.dump(pyproject, open('pyproject.toml', 'w'))"

    - name: Build package
      run: python -m build --outdir dist/

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
