name: Release Please

on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: write
  actions: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: GoogleCloudPlatform/release-please-action@v4
      with:
        token: ${{ secrets.RELEASE_PLEASE_PAT }}
        release-type: python
        config-file: release-please-config.json
