name: Release Please

on:
  push:
    branches:
      - main

permissions:
    contents: write
    pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: 'python'  # Change this according to your project type, e.g., 'python', 'go'
          
      
