name: Release Please

on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: write
  actions: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install build
    - name: Build project
      run: python -m build --outdir dist/
    - name: Create Release PR
      id: release_pr
      uses: GoogleCloudPlatform/release-please-action@v4
      with:
        token: ${{ secrets.RELEASE_PLEASE_PAT }}
        release-type: python
        config-file: release-please-config.json
    - name: Get PR title
      id: get_pr_title
      run: |
        PR_TITLE=$(gh pr view https://github.com/${{ github.repository }}/pull/${{ steps.release_pr.outputs.pull_request_number }} --json title -q '.title')
        echo "::set-output name=pr_title::$PR_TITLE"
      env:
        GH_TOKEN: ${{ secrets.RELEASE_PLEASE_PAT }}
    - name: Extract version from PR title
      id: extract_version
      run: |
        VERSION=$(echo "${{ steps.get_pr_title.outputs.pr_title }}" | grep -oP 'v\K.*')
        echo "::set-output name=version::$VERSION"
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_PAT }}
      with:
        tag_name: ${{ steps.extract_version.outputs.version }}
        release_name: Release ${{ steps.extract_version.outputs.version }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/
        asset_name: dist.zip
        asset_content_type: application/zip