name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Create Release PR
      id: release
      uses: GoogleCloudPlatform/release-please-action@v4
      with:
        token: ${{ secrets.RELEASE_PLEASE_PAT }}
        release-type: python
        config-file: release-please-config.json
  
    - name: Update pyproject version
      if: ${{ steps.release.outputs.release_created }}
      run: |
        pip install toml
        python -c "import toml; pyproject = toml.load('pyproject.toml'); pyproject['project']['version'] = '${{ steps.release.outputs.tag_name }}'.strip()[1:]; toml.dump(pyproject, open('pyproject.toml', 'w'))"

    - name: Install dependencies
      if: ${{ steps.release.outputs.release_created }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install build

    - name: Build project
      if: ${{ steps.release.outputs.release_created }}
      run: python -m build --outdir dist/

    - name: Upload Release Artifact
      if: ${{ steps.release.outputs.release_created }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload ${{ steps.release.outputs.tag_name }} ./dist/*.whl ./dist/*.tar.gz
